server:
  port: 7000

raft:
  servers:
    - "localhost:5001"
    - "localhost:6001"
    - "localhost:7001"
  self: "localhost:7001"

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
