server:
  port: 5000

raft:
  servers:
    - "localhost:5001"
    - "localhost:6001"
    - "localhost:7001"
  self: "localhost:5001"
  electionTimeout: 7000
  heartBeatFrequent: 5000
  log: "log1.json"

library:
  address: "library1"

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
