server:
  port: 6000

raft:
  servers:
    - "localhost:5001"
    - "localhost:6001"
    - "localhost:7001"
  self: "localhost:6001"
  electionTimeout: 15000
  heartBeatFrequent: 5000
  log: "log2.json"

library:
  address: "library2"

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
