server:
  port: 5000

raft:
  servers:
    - "localhost:5001"
    - "localhost:6001"
    - "localhost:7001"
  self: "localhost:5001"
  electionTimeout: 15000
  heartBeatFrequent: 5000

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
