server:
  port: 9200

# common log level
logging:
  level:
    root: INFO
  file:
    name: "log1.log"


raft:
  servers:
    - "localhost:9101"
    - "localhost:9201"
    - "localhost:9301"
  serversSpringAddress:
    - "localhost:9100"
    - "localhost:9200"
    - "localhost:9300"
  self: "localhost:9101"

library:
  address: "libraries/basicLibrary1"

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
